#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias b4="${ZDOTDIR:-$HOME}/src/b4/b4.sh"

source /run/current-system/sw/share/fzf/key-bindings.zsh
source /run/current-system/sw/share/fzf/completion.zsh
eval "$(direnv hook zsh)"

